### ISSUE TITLE
Implement draggable for recycleview

### ISSUE THREAD

**Issue by kj21012** [kivy-garden/draggable#25]
Drag and drop example for scrollbiew exists, but not for recycleview.

**Comment by Fretless14** [comment]
works for me. Unless you're talking about making the whole RecycleView object draggable, haven't looked into whether you can do that or not. Pretty sure you can though, just make a custom class like any other object and add the inheritance

**Comment by gottadiveintopython** [comment]
I don't know what type of example you want to see.
If you want to make `RecycleView` re-orderable, you'll most likely need to create your own `RecycleView`, which would require lots of work. Otherwise, it's not hard to do.
